[versions]
compose-plugin = "1.6.0-alpha01"
kotlin = "1.9.21"

[libraries]

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }